SERVICE_OPTIONS = {
    "bin collection": ("bin_collection", "Bin collection"),
    "blue badge": ("blue_badge", "Blue Badge"),
    "contact services": ("contact_services", "Contact services"),
    "council tax": ("council_tax", "Council tax"),
    "library services": ("libraries", "Library services"),
    "planning applications": ("planning_applications", "Planning applications"),
    "school admissions": ("school_admissions", "School admissions"),
    "benefits support": ("benefits_support", "Benefits support"),
    "something else": ("something_else", "Something else"),
}

INTENT_GROUPS = {
    "bin_collection": [
        "check_bin_collection_dates",
        "check_bin_day_general",
        "report_bin_not_collected_info",
        "service_disruption_bin",
        "assisted_collection_request",
        "bin_collection_outside_area",
        "bin_recycling_guidance",
    ],
    "benefits_support": [
        "housing_benefit_eligibility",
        "apply_housing_benefit_ctr",
        "discretionary_housing_payment",
        "benefits_myinfo_access",
        "submit_benefit_evidence",
        "report_change_of_circumstances",
        "benefit_appeal_or_reconsideration",
        "benefits_support_contact",
        "benefits_calculator",
    ],
    "blue_badge": [
        "blue_badge_apply",
        "blue_badge_eligibility",
        "blue_badge_cost",
        "blue_badge_renewal",
        "blue_badge_replacement",
        "blue_badge_parking_rules",
        "blue_badge_misuse",
        "blue_badge_organisations",
        "blue_badge_contact",
    ],
    "contact_services": [],
    "council_tax": [
        "find_council_tax_band",
        "check_council_tax_balance",
        "check_council_tax_amount",
        "council_tax_payment",
        "council_tax_payment_methods",
        "council_tax_payment_problem",
        "apply_council_tax_discount",
        "council_tax_general_discounts",
        "report_move_council_tax",
        "council_tax_change_details",
        "council_tax_appeal",
        "council_tax_arrears_help",
        "council_tax_general_info",
        "set_up_direct_debit",
        "change_payment_date_or_instalments",
        "apply_student_discount",
        "council_tax_reduction_support",
        "empty_property_council_tax",
        "contact_council_tax_team",
    ],
    "libraries": [
        "library_finder",
        "library_hours",
        "library_membership",
        "library_catalogue",
        "library_events",
        "library_services",
        "library_home_service",
        "library_contact",
    ],
    "planning_applications": [],
    "school_admissions": [
        "school_finder",
        "primary_admissions",
        "secondary_admissions",
        "school_admissions_dates",
        "school_appeals",
        "in_year_admissions",
        "contact_admissions",
        "school_admissions_criteria",
        "school_admissions_process",
    ],
    "something_else": [],
}

INTENT_ALIASES = {
    # Bin collection aliases
    "report_missed_bin": "report_bin_not_collected_info",
    "missed_bin": "report_bin_not_collected_info",
    "bin_collection_schedule": "check_bin_collection_dates",
    "check_bin_collection": "check_bin_collection_dates",
    "check_next_bin_collection": "check_bin_collection_dates",
    "bin_service_disruption": "service_disruption_bin",
    "service_disruption": "service_disruption_bin",
    "assisted_bin_collection": "assisted_collection_request",
    "general_bin_information": "check_bin_day_general",

    # Benefits aliases
    "housing_benefit_apply": "apply_housing_benefit_ctr",
    "benefits_account_access": "benefits_myinfo_access",
    "change_of_circumstances": "report_change_of_circumstances",
    "benefits_appeal": "benefit_appeal_or_reconsideration",
    "contact_benefits_support": "benefits_support_contact",

    # Library aliases
    "find_library":             "library_finder",
    "library_search":           "library_finder",
    "nearest_library":          "library_finder",
    "library_opening_hours":    "library_hours",
    "library_open":             "library_hours",
    "join_library":             "library_membership",
    "library_card":             "library_membership",
    "search_books":             "library_catalogue",
    "reserve_book":             "library_catalogue",
    "renew_book":               "library_catalogue",
    "library_ebooks":           "library_catalogue",
    "library_activities":       "library_events",
    "library_storytime":        "library_events",
    "library_computers":        "library_services",
    "library_wifi":             "library_services",
    "home_library":             "library_home_service",
    "housebound_library":       "library_home_service",
    "contact_library":          "library_contact",

    # Blue Badge aliases
    "apply_blue_badge":           "blue_badge_apply",
    "blue_badge_application":     "blue_badge_apply",
    "blue_badge_eligibility_check": "blue_badge_eligibility",
    "qualify_blue_badge":         "blue_badge_eligibility",
    "blue_badge_fee":             "blue_badge_cost",
    "renew_blue_badge":           "blue_badge_renewal",
    "blue_badge_expired":         "blue_badge_renewal",
    "replace_blue_badge":         "blue_badge_replacement",
    "lost_blue_badge":            "blue_badge_replacement",
    "blue_badge_parking":         "blue_badge_parking_rules",
    "disabled_parking":           "blue_badge_parking_rules",
    "report_blue_badge_misuse":   "blue_badge_misuse",
    "blue_badge_fraud":           "blue_badge_misuse",
    "org_blue_badge":             "blue_badge_organisations",
    "contact_blue_badge":         "blue_badge_contact",

    # School admissions aliases
    "find_school":              "school_finder",
    "school_search":            "school_finder",
    "locate_school":            "school_finder",
    "apply_primary":            "primary_admissions",
    "apply_secondary":          "secondary_admissions",
    "school_dates":             "school_admissions_dates",
    "admissions_deadline":      "school_admissions_dates",
    "school_appeal":            "school_appeals",
    "appeal_school":            "school_appeals",
    "in_year_transfer":         "in_year_admissions",
    "transfer_school":          "in_year_admissions",
    "contact_school_admissions":"contact_admissions",
    "admissions_criteria":      "school_admissions_criteria",
    "how_apply_school":         "school_admissions_process",

    # Council tax aliases
    "council_tax_band": "find_council_tax_band",
    "find_band": "find_council_tax_band",
    "check_band": "find_council_tax_band",
    "check_council_tax_bill": "check_council_tax_balance",
    "council_tax_balance": "check_council_tax_balance",
    "pay_council_tax": "council_tax_payment",
    "council_tax_pay": "council_tax_payment",
    "payment_methods_council_tax": "council_tax_payment_methods",
    "council_tax_help_paying": "council_tax_payment_problem",
    "single_person_discount": "apply_council_tax_discount",
    "council_tax_discount": "apply_council_tax_discount",
    "council_tax_reduction": "council_tax_general_discounts",
    "move_house_council_tax": "report_move_council_tax",
    "change_council_tax_details": "council_tax_change_details",
    "appeal_council_tax": "council_tax_appeal",
    "council_tax_arrears": "council_tax_arrears_help",
    "council_tax_info": "council_tax_general_info",
}

INTENT_LABELS = {
    # Bin collection labels
    "check_bin_collection_dates": "checking your next bin collection date",
    "check_bin_day_general": "checking your usual bin collection day",
    "report_bin_not_collected_info": "reporting a missed bin",
    "service_disruption_bin": "bin collection disruption",
    "assisted_collection_request": "assisted bin collection",
    "bin_collection_outside_area": "bin collection outside Bradford district",
    "bin_recycling_guidance": "bin and recycling guidance",

    # Benefits labels
    "benefits_calculator": "benefits calculator",
    "housing_benefit_eligibility": "housing benefit eligibility",
    "apply_housing_benefit_ctr": "applying for housing benefit or council tax reduction",
    "discretionary_housing_payment": "discretionary housing payment",
    "benefits_myinfo_access": "accessing your benefits account",
    "submit_benefit_evidence": "submitting benefit evidence",
    "report_change_of_circumstances": "reporting a change of circumstances",
    "benefit_appeal_or_reconsideration": "appealing or asking for reconsideration of a benefits decision",
    "benefits_support_contact": "contacting benefits support",

    # Council tax labels
    "find_council_tax_band": "finding your Council Tax band",
    "check_council_tax_balance": "checking your Council Tax balance",
    "council_tax_payment": "paying your Council Tax",
    "council_tax_payment_methods": "Council Tax payment methods",
    "council_tax_payment_problem": "help with Council Tax payment problems",
    "apply_council_tax_discount": "applying for a Council Tax discount",
    "council_tax_general_discounts": "Council Tax discounts and reductions",
    "report_move_council_tax": "reporting a Council Tax move",
    "council_tax_change_details": "changing Council Tax account details",
    "council_tax_appeal": "making a Council Tax appeal",
    "council_tax_arrears_help": "help with Council Tax arrears",
    "council_tax_general_info": "general Council Tax information",
    "check_council_tax_amount": "checking Council Tax band amounts",
    "set_up_direct_debit": "setting up a Direct Debit for Council Tax",
    "change_payment_date_or_instalments": "changing Council Tax payment date or instalments",
    "apply_student_discount": "applying for a student Council Tax discount",
    "council_tax_reduction_support": "Council Tax reduction support",
    "empty_property_council_tax": "Council Tax for empty properties",
    "contact_council_tax_team": "contacting the Council Tax team",

    # Library labels
    "library_finder":       "finding a Bradford library",
    "library_hours":        "library opening hours",
    "library_membership":   "joining the library",
    "library_catalogue":    "searching books and the catalogue",
    "library_events":       "library events and activities",
    "library_services":     "library facilities",
    "library_home_service": "Home Library Service",
    "library_contact":      "contacting a library",

    # Blue Badge labels
    "blue_badge_apply":         "applying for a Blue Badge",
    "blue_badge_eligibility":   "Blue Badge eligibility",
    "blue_badge_cost":          "Blue Badge cost",
    "blue_badge_renewal":       "renewing a Blue Badge",
    "blue_badge_replacement":   "replacing a lost or damaged Blue Badge",
    "blue_badge_parking_rules": "Blue Badge parking rules",
    "blue_badge_misuse":        "reporting Blue Badge misuse",
    "blue_badge_organisations": "Blue Badge for organisations",
    "blue_badge_contact":       "contacting the Blue Badge team",

    # School admissions labels
    "school_finder":              "finding a Bradford school",
    "primary_admissions":         "primary school admissions",
    "secondary_admissions":       "secondary school admissions",
    "school_admissions_dates":    "school admissions key dates and deadlines",
    "school_appeals":             "school admissions appeals",
    "in_year_admissions":         "in-year school admissions and transfers",
    "contact_admissions":         "contacting the admissions team",
    "school_admissions_criteria": "how school places are allocated",
    "school_admissions_process":  "the school admissions process",
}

LOW_CONFIDENCE_THRESHOLD = 0.20
MID_CONFIDENCE_THRESHOLD = 0.35

FLOW_INTENTS = {
    "check_bin_day_general",
    "report_bin_not_collected_info",
    "service_disruption_bin",
    "assisted_collection_request",
    "bin_collection_outside_area",
    "housing_benefit_eligibility",
    "apply_housing_benefit_ctr",
    "discretionary_housing_payment",
    "benefits_myinfo_access",
    "submit_benefit_evidence",
    "report_change_of_circumstances",
    "benefit_appeal_or_reconsideration",
    "benefits_support_contact",
    "find_council_tax_band",
    "council_tax_payment",
    "council_tax_payment_methods",
    "council_tax_payment_problem",
    "apply_council_tax_discount",
    "council_tax_general_discounts",
    "report_move_council_tax",
    "council_tax_change_details",
    "council_tax_appeal",
    "council_tax_arrears_help",
    "council_tax_general_info",
    "check_council_tax_amount",
    "set_up_direct_debit",
    "change_payment_date_or_instalments",
    "apply_student_discount",
    "council_tax_reduction_support",
    "empty_property_council_tax",
    "contact_council_tax_team",
    "library_finder",
    "library_hours",
    "library_membership",
    "library_catalogue",
    "library_events",
    "library_services",
    "library_home_service",
    "library_contact",
    "blue_badge_apply",
    "blue_badge_eligibility",
    "blue_badge_cost",
    "blue_badge_renewal",
    "blue_badge_replacement",
    "blue_badge_parking_rules",
    "blue_badge_misuse",
    "blue_badge_organisations",
    "blue_badge_contact",
    "school_finder",
    "primary_admissions",
    "secondary_admissions",
    "school_admissions_dates",
    "school_appeals",
    "in_year_admissions",
    "contact_admissions",
    "school_admissions_criteria",
    "school_admissions_process",
}